---
version: "2.1"
services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - URL=pberger.online
      - EMAIL=Peter.Bergeron@gmail.com
      - SUBDOMAINS=www,overseerr,plex,ombi,emby,ollama,mind
      - VALIDATION=http
      - EXTRA_DOMAINS=lamei.wang
    volumes:
      - /home/peter/swag:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
  ollamauth:
    image: python:latest
    container_name: ollamauth
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./auth-endpoint.py
        target: /usr/bin/auth-endpoint.py
      - type: bind
        source: ./tokeup
        target: /usr/bin/tokeup
    ports:
      - 3000:3000
    command: sh -c "pip install Flask && python3 /usr/bin/auth-endpoint.py"
