---
version: "2.1"
services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/NewYork
      - URL=pberger.online
      - SUBDOMAINS=www,overseerr,plex,ombi,emby
      - VALIDATION=http
    # - CERTPROVIDER= #optional
    # - DNSPLUGIN=cloudflare #optional
    # - DUCKDNSTOKEN=<token> #optional
    # - EMAIL=<e-mail> #optional
    # - ONLY_SUBDOMAINS=false #optional
    # - EXTRA_DOMAINS=<extradomains> #optional
    # - STAGING=false #optional
    volumes:
      - /home/peter/swag:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
